Add lock icon on current attempt letters
joglr/ordle pull request #44
Opened 2023-06-07 11:57 UTC by joglr

2023-06-07 11:58 UTC, joglr commented
#### 📝 Changed routes:


| [**/**](https://ordle-qok01filf-joglr.vercel.app/) |
|:-:|
|<a href="https://ordle-qok01filf-joglr.vercel.app/"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/IoJJ0toX00u_0Gu4iS7vLkgOmrpzm2KOV9wM9vamzIDyAZy_5qBZnvsNB5S5TeF8VYraztPj-8Hvpay0hqQHVw.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/vQgYlzoC4LB77qQqEwxMp6hOkiSvtR9gFs9ZujmqvEGibF3GochWoQV_SRipoXArEpwtXpyVTjeg6Dktab00jg.png">(view full size)</a> |







Commit 19a3d0135f84ce7298c2f3ba75e7e41ba521928d (https://ordle-qok01filf-joglr.vercel.app).

2023-06-07 22:30 UTC, rasmusroessum requested changes
Changing from <Square> to <button> gives the UI a little change. Maybe we should put the button in the others or change the Square?

2023-06-07 22:30 UTC, rasmusroessum commented on src/pages/index.tsx
> +        <button
Making this change adds a little change in the height of the div/button. I think this should be fixed

2023-06-07 22:33 UTC, rasmusroessum commented on src/pages/index.tsx
> +        <button
![image](https://github.com/joglr/ordle/assets/35430583/81bfd481-d8b7-4edd-aaee-033400144f54)

<img width="421" alt="image" src="https://github.com/joglr/ordle/assets/35430583/ed918681-0bc8-4102-9461-8e1130cfa074">

2023-06-08 06:37 UTC, joglr commented on src/pages/index.tsx
> +        <button
We need a proper CSS reset that ensures that this is not a problem.

2023-06-08 09:43 UTC, joglr commented on src/pages/index.tsx
> +        <button
![image](https://github.com/joglr/ordle/assets/1959615/fdb6cb45-681c-4784-8ab3-5660d728ed46)
Seems this is also an issue on the main branch.

2023-06-09 07:12 UTC, merged